-- -------------------------
-- PRUEBA TECNICA
-- -------------
CREATE
DATABASE DB_EMPLOYEES_MS;
USE
DB_EMPLOYEES_MS;

CREATE TABLE TBL_EMPLOYEES
(
    ID         BIGINT      NOT NULL AUTO_INCREMENT,
    BIRTH_DATE DATETIME DEFAULT NULL,
    FIRST_NAME VARCHAR(14) NOT NULL,
    LAST_NAME  VARCHAR(16) NOT NULL,
    SEX        ENUM('M', 'F'),
    HIRE_DATE  DATETIME DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_DEPARTMENTS
(
    ID        BIGINT      NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_DEPT_MANAGER
(
    ID            BIGINT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_ID   BIGINT NOT NULL,
    FROM_DATE     DATETIME DEFAULT NULL,
    TO_DATES      DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES TBL_DEPARTMENTS (ID)
);



CREATE TABLE TBL_DEPT_EMP
(
    ID            BIGINT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_ID   BIGINT NOT NULL,
    FROM_DATE     DATETIME DEFAULT NULL,
    TO_DATES      DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES TBL_DEPARTMENTS (ID)
);

CREATE TABLE TBL_SALARIES
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID BIGINT NOT NULL,
    SALARY      INT    NOT NULL,
    FROM_DATE   DATETIME DEFAULT NULL,
    TO_DATES    DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID)
);

CREATE TABLE TBL_TITLES
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID BIGINT      NOT NULL,
    TITLE       VARCHAR(50) NOT NULL,
    FROM_DATE   DATETIME DEFAULT NULL,
    TO_DATES    DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID)
);

ALTER TABLE DB_EMPLOYEES_MS.TBL_EMPLOYEES
    ADD EMAIL varchar(100) NULL;
ALTER TABLE DB_EMPLOYEES_MS.TBL_EMPLOYEES CHANGE EMAIL EMAIL varchar (100) NULL AFTER LAST_NAME;
ALTER TABLE DB_EMPLOYEES_MS.TBL_SALARIES
    ADD COMMISSION BIGINT NULL;
ALTER TABLE DB_EMPLOYEES_MS.TBL_SALARIES CHANGE COMMISSION COMMISSION BIGINT NULL AFTER SALARY;


SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPARTMENTS;
SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPT_EMP;
SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPT_MANAGER;
SELECT *
FROM DB_EMPLOYEES_MS.TBL_EMPLOYEES;
SELECT *
FROM DB_EMPLOYEES_MS.TBL_SALARIES;
SELECT *
FROM DB_EMPLOYEES_MS.TBL_TITLES tt



SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPARTMENTS D
         INNER JOIN DB_EMPLOYEES_MS.TBL_DEPT_EMP DE
                    ON
                        D.ID = DE.DEPARTMENT_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_EMPLOYEES E
                    ON
                        E.ID = DE.EMPLOYEE_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_TITLES T
                    ON
                        T.EMPLOYEE_ID = E.ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_SALARIES S
                    ON
                        S.EMPLOYEE_ID = DE.EMPLOYEE_ID
WHERE D.ID = 1;

--

SELECT E.FIRST_NAME,
       E.LAST_NAME,
       E.EMAIL,
       TL.TITLE,
       S.SALARY,
       S.COMMISSION,
       CONCAT(EM.FIRST_NAME, " ", EM.LAST_NAME)
FROM DB_EMPLOYEES_MS.TBL_TITLES T
         INNER JOIN DB_EMPLOYEES_MS.TBL_DEPT_MANAGER DM
                    ON
                        DM.EMPLOYEE_ID = T.EMPLOYEE_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_DEPT_EMP DE
                    ON
                        DE.DEPARTMENT_ID = DE.DEPARTMENT_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_EMPLOYEES E
                    ON
                        E.ID = DE.EMPLOYEE_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_EMPLOYEES EM
                    ON
                        EM.ID = T.EMPLOYEE_ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_TITLES TL
                    ON
                        TL.EMPLOYEE_ID = E.ID
         INNER JOIN DB_EMPLOYEES_MS.TBL_SALARIES S
                    ON
                        S.EMPLOYEE_ID = E.ID
WHERE T.TITLE = 'Ingeniero de desarrollo'
  AND T.EMPLOYEE_ID = 1;

SELECT *
FROM DB_EMPLOYEES_MS.TBL_TITLES T
WHERE T.TITLE = 'Ingeniero de desarrollo'
  AND T.EMPLOYEE_ID = 1;

SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPT_MANAGER
WHERE EMPLOYEE_ID = 1;

SELECT *
FROM DB_EMPLOYEES_MS.TBL_DEPT_EMP DE
WHERE DE.DEPARTMENT_ID = 1;

SELECT *
FROM DB_EMPLOYEES_MS.TBL_EMPLOYEES te
WHERE ID = 2;