-- -------------------------
-- PRUEBA TECNICA
-- -------------
DROP TABLE IF EXISTS TBL_DEPT_MANAGER;
DROP TABLE IF EXISTS TBL_DEPT_EMP;
DROP TABLE IF EXISTS TBL_SALARIES;
DROP TABLE IF EXISTS TBL_TITLES;
DROP TABLE IF EXISTS TBL_DEPARTMENTS;
DROP TABLE IF EXISTS TBL_EMPLOYEES;

CREATE TABLE TBL_EMPLOYEES
(
    ID         BIGINT      NOT NULL AUTO_INCREMENT,
    BIRTH_DATE DATETIME DEFAULT NULL,
    FIRST_NAME VARCHAR(14) NOT NULL,
    LAST_NAME  VARCHAR(16) NOT NULL,
    EMAIL VARCHAR (100) NULL,
    SEX        ENUM('M', 'F'),
    HIRE_DATE  DATETIME DEFAULT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_DEPARTMENTS
(
    ID        BIGINT      NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR(40) NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE TBL_DEPT_MANAGER
(
    ID            BIGINT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_ID   BIGINT NOT NULL,
    FROM_DATE     DATETIME DEFAULT NULL,
    TO_DATES      DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES TBL_DEPARTMENTS (ID)
);



CREATE TABLE TBL_DEPT_EMP
(
    ID            BIGINT NOT NULL AUTO_INCREMENT,
    DEPARTMENT_ID BIGINT NOT NULL,
    EMPLOYEE_ID   BIGINT NOT NULL,
    FROM_DATE     DATETIME DEFAULT NULL,
    TO_DATES      DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID),
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES TBL_DEPARTMENTS (ID)
);

CREATE TABLE TBL_SALARIES
(
    ID          BIGINT NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID BIGINT NOT NULL,
    SALARY      INT    NOT NULL,
    COMMISSION BIGINT NULL,
    FROM_DATE   DATETIME DEFAULT NULL,
    TO_DATES    DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID)
);

CREATE TABLE TBL_TITLES
(
    ID          BIGINT      NOT NULL AUTO_INCREMENT,
    EMPLOYEE_ID BIGINT      NOT NULL,
    TITLE       VARCHAR(50) NOT NULL,
    FROM_DATE   DATETIME DEFAULT NULL,
    TO_DATES    DATETIME DEFAULT NULL,
    PRIMARY KEY (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES TBL_EMPLOYEES (ID)
);